server:
  port: 7001
  servlet:
    context-path: /user

#数据源配置
spring:
  application:
    name: microservice-provider-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springcloud
    username: root
    password: 123456

