server:
  port: 7005
  context-path: /

eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: microservice-consumer-movie  #客户端服务名
    instance-id: microservice-consumer-movie:7005 #客户端实例名称
    prefer-ip-address: true #显示IP
  client:
    service-url:
      # 单机 defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
      defaultZone: http://localhost:7201/eureka
